trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  workingDirectory: "./"
  displayName: "npm install"

- script: |
    npm run lint
  workingDirectory: "./"
  displayName: "tslint"

- script: |
    npm run test
  workingDirectory: "./"
  displayName: "npm run test"
